apiVersion: v1
kind: LimitRange
metadata:
  name: project-n-lr
  namespace: project-n
  labels:
    app.kubernetes.io/name: project-n
    app.kubernetes.io/part-of: project-n
    app.kubernetes.io/managed-by: kubectl
spec:
  limits:
    - type: Container
      default:
        # Applied as the limit if the developer does not set one
        cpu: 500m
        memory: 512Mi
      defaultRequest:
        # Applied as the request if the developer does not set one
        cpu: 200m
        memory: 256Mi
